name: Secrets Demo

on:
  push:
    branches:
      - main

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret safely
        run: |
          echo "Secret is available"
          echo "Length of secret: ${#MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}