name: Jobs and Steps Demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 – Check OS
        run: |
          uname -a
          whoami

      - name: Step 2 – Create a file
        run: |
          echo "This file was created in Step 2" > demo.txt
          ls -l

      - name: Step 3 – Read the file
        run: |
          cat demo.txt