name: First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
  job2:
    runs-on: ubuntu-latest

    step1:
      - name: Print Hello
      - run: echo "Step 1"
    step2:
      - name: Print Hello
      - run: echo "Step 2"